name: continuous integration

on: [push, pull_request]

jobs:
  run-mvn-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: run the maven tests
        run: mvn verify
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
