name: continuous integration

on: [push, pull_request]

jobs:
  run-mvn-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@2.3.4
      - name: run the maven tests
        run: mvn verify
